name: daily_brief
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  cached_network_image: ^3.3.1
  provider: ^6.1.2
  connectivity_plus: ^5.0.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  flutter_bloc: ^8.1.5
  hive: ^2.2.3
  path_provider: ^2.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
    - assets/